name: Build and Push Docker Image

on:
  workflow_dispatch:
  #push:
    #branches:
      # - main  # Mude para a branch desejada

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3  # Versão mais atual do checkout

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Versão mais atual do docker login
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build \
          --build-arg GIT_TOKEN=${{ secrets.GIT_TOKEN }} \
          --build-arg GIT_USERNAME=${{ secrets.GIT_USERNAME }} \
          --build-arg GIT_EMAIL=${{ secrets.GIT_EMAIL }} \
          -t celsosjunior/docker-ansible:latest .

    - name: Push Docker image
      run: |
        docker push celsosjunior/docker-ansible:latest
